### ISSUE TITLE
Visual link in results page not opening layer in marine planner

### ISSUE THREAD

**Issue by fishytodd** [WCGA/Marine-Planner#39]
I recently loaded a number of fishing effort layers coming from OSU Active Tectonics lab (http://portal.westcoastoceans.org/discover/#?s=OSU%20Active%20Tectonics%20Laboratory), included the geoportal id in the MP admin, and the "Visualize" link pops up in the catalog results page. However, when I click on the visualize link for any of these records, MP opens up in a new window but the layer does not open with it. It just seems to be for these new layers. Not sure what the difference is, all the same setting are being used int eh MP admin.

**Comment by fishytodd** [comment]
another example of the bug

http://portal.westcoastoceans.org/discover/#?text=blue%20whale,%20pa

**Comment by fishytodd** [comment]
Here is an example link:
http://maps.westcoastoceans.org/visualize/#x=-124.56&y=40.46&z=5&logo=true&basemap=ESRI+Ocean&tab=data&legends=false&layers=true&filters%5Bfrom%5D=2012-02-05&filters%5Bto%5D=2015-02-05

Here’s one of the links from OSU substrate that is working
http://maps.westcoastoceans.org/visualize/#x=-124.56&y=40.46&z=5&logo=false&dls%5B%5D=true&dls%5B%5D=0.5&dls%5B%5D=194&basemap=ESRI+Ocean&themes%5Bids%5D%5B%5D=11&tab=active&legends=false&layers=true&filters%5Bfrom%5D=2012-02-05&filters%5Bto%5D=2015-02-05

**Comment by sfletche** [comment]
It appears the problem was with a mismatching of slugs generated Ocean Data Portal and also the Marine Planner.

I just pushed a patch that should fix this problem.

See the following
http://maps.westcoastoceans.org/visualize/#blue-whale-pacific-summer
http://maps.westcoastoceans.org/visualize/#extent-of-mid-water-trawling-2002-2006-noaa-2012

Note:  You might need to clear your cache...
